1. What is a Python library? Why do we use Python libraries?


What is a Python library?
 * A Python library is essentially a collection of pre-written code, including modules and packages, that provides specific functionalities.
 * Think of it as a toolkit containing ready-to-use tools that you can incorporate into your Python programs.
 * These libraries save developers from having to write code from scratch for common tasks.


Why do we use Python libraries?
 * Code Reusability:
   * Libraries allow you to reuse existing code, which saves time and effort. Instead of writing the same code repeatedly, you can simply import and use the functions and classes provided by a library.
 * Increased Efficiency:
   * Libraries provide optimized and tested code, which can improve the efficiency and performance of your programs.
 * Expanded Functionality:
   * Python libraries offer a vast range of functionalities, from basic tasks like file manipulation to advanced tasks like machine learning and data visualization.
 * Simplified Development:
   * Libraries simplify the development process by providing high-level abstractions and tools that make it easier to solve complex problems.
 * Community Support:
   * Python has a very large and active community, which means there are a huge number of high quality libraries available.
 * Specialized Tasks:
   * Libraries allow programmers to easily carry out specialized tasks. For example, in data science, libraries like Pandas and NumPy are essential for data manipulation and analysis.

2. What is the difference between Numpy array and List?


Python Lists:
 * Flexibility:
   * Lists are incredibly versatile. They can hold elements of various data types within the same list (e.g., integers, strings, other lists).
   * They are dynamic, meaning their size can change easily. You can add or remove elements as needed.
 * General-Purpose:
   * Lists are a fundamental part of Python and are used for a wide range of general-purpose programming tasks.
 * Performance:
   * For numerical computations, especially with large datasets, lists can be relatively slow.


   
NumPy Arrays:
 * Homogeneity:
   * NumPy arrays are designed to hold elements of the same data type. This homogeneity is crucial for efficient numerical operations.
 * Numerical Computing:
   * NumPy arrays are optimized for numerical computations. They provide powerful mathematical functions and operations.
   * They support "vectorized" operations, which means you can perform operations on entire arrays at once, significantly speeding up computations.
 * Memory Efficiency:
   * Due to their homogeneous nature and contiguous memory allocation, NumPy arrays are more memory-efficient than lists, especially for large datasets.
 * Performance:
   * NumPy arrays are significantly faster than lists for numerical operations.

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [26]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

#Find the shape
shape = arr.shape
print(f"Shape : {shape}")

#Find the size
size = arr.size
print(f"size : {size}")

#Find the dimension
dimension = arr.ndim
print(f"dimension : {dimension}")

Shape : (3, 4)
size : 12
dimension : 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [27]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
first_row = arr[0]
print(f"First row : {first_row}")

First row : [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [28]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
element = arr[2,3] #indexing start from 0
print(f"the element at the third row and fourth column : {element}")

the element at the third row and fourth column : 12


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [29]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
odd_indexed_elements = arr[:,1::2]
#Select all rows and columns starting from index 1 with a step of 2
print(f"All odd-indexed elements : \n{odd_indexed_elements}")

All odd-indexed elements : 
[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?


In [30]:
random_matrix = np.random.rand(3,3)
print(f"a random 3x3 matrix with values between 0 and 1 : \n{random_matrix}")

a random 3x3 matrix with values between 0 and 1 : 
[[0.11242208 0.233635   0.38285841]
 [0.7837611  0.11153443 0.35826489]
 [0.84755497 0.80219377 0.1832312 ]]


8. Describe the difference between np.random.rand and np.random.randn?

1. np.random.rand()
 * Distribution: Generates random numbers from a uniform distribution over the half-open interval [0, 1). This means that every number within that range has an equal probability of being generated.
 * Arguments: Takes the dimensions of the output array as arguments (e.g., np.random.rand(3) for a 1D array of length 3, np.random.rand(2, 4) for a 2x4 matrix).
 * Output: Returns an array filled with random floats between 0 and 1.


2. np.random.randn()
 * Distribution: Generates random numbers from the standard normal distribution (also known as the Gaussian distribution). This distribution has a mean of 0 and a standard deviation of 1.
 * Arguments: Takes the dimensions of the output array as arguments (similar to np.random.rand).
 * Output: Returns an array filled with random floats from the standard normal distribution. This means that values close to 0 are more likely to be generated, and values further away from 0 (both positive and negative) are less likely.

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [31]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

expanded_array = np.expand_dims(arr,axis = 0) 
#adding a dimension at the beginning (axis = 0)

print(f"Original Array Shape : {arr.shape}")

print(f"Expanded Array Shape : {expanded_array.shape}")

print(f"Expanded array : \n{expanded_array}")

Original Array Shape : (3, 4)
Expanded Array Shape : (1, 3, 4)
Expanded array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [32]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
transposed_array = arr.T
print(f"Original Array : \n{arr}\n")

print(f"Transposed Array : \n{transposed_array}")

Original Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array : 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Perform the following operation using Python :

1. Index wise multiplication


In [33]:
Matrix_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
Matrix_B = np.array([[16,15,14,13],[12,11,10,9],[8,7,6,5],[4,3,2,1]])

index_wise_mul = Matrix_A * Matrix_B
print(f"Index Wise Multiplication : \n{index_wise_mul}")

Index Wise Multiplication : 
[[16 30 42 52]
 [60 66 70 72]
 [72 70 66 60]
 [52 42 30 16]]


2. Matrix multiplication


In [34]:
Matrix_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
Matrix_B = np.array([[16,15,14,13],[12,11,10,9],[8,7,6,5],[4,3,2,1]])

matrix_mul = Matrix_A @ Matrix_B
print(f"Matrix Multiplication : \n{matrix_mul}")

Matrix Multiplication : 
[[ 80  70  60  50]
 [240 214 188 162]
 [400 358 316 274]
 [560 502 444 386]]


3. Add both the matrics


In [35]:
Matrix_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
Matrix_B = np.array([[16,15,14,13],[12,11,10,9],[8,7,6,5],[4,3,2,1]])

matrix_add = Matrix_A + Matrix_B
print(f"Matrix Addition : \n{matrix_add}")

Matrix Addition : 
[[17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]]


4. Subtract matrix B from A


In [36]:
Matrix_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
Matrix_B = np.array([[16,15,14,13],[12,11,10,9],[8,7,6,5],[4,3,2,1]])

matrix_subtract = Matrix_A - Matrix_B
print(f"Matrix Subtraction : \n{matrix_subtract}")

Matrix Subtraction : 
[[-15 -13 -11  -9]
 [ -7  -5  -3  -1]
 [  1   3   5   7]
 [  9  11  13  15]]


5. Divide Matrix B by A

In [37]:
Matrix_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
Matrix_B = np.array([[16,15,14,13],[12,11,10,9],[8,7,6,5],[4,3,2,1]])

matrix_divide = Matrix_B / Matrix_A
print(f"Matrix Division : \n{matrix_divide:}")

Matrix Division : 
[[16.          7.5         4.66666667  3.25      ]
 [ 2.4         1.83333333  1.42857143  1.125     ]
 [ 0.88888889  0.7         0.54545455  0.41666667]
 [ 0.30769231  0.21428571  0.13333333  0.0625    ]]


12. Which function in Numpy can be used to swap the byte order of an array?


The NumPy function used to swap the byte order of an array is numpy.ndarray.byteswap().
Explanation:
 * Byte Order: Refers to how multi-byte data types (like integers greater than 8 bits) are stored in memory. There are two primary byte orders:
   * Big-endian: The most significant byte is stored first.
   * Little-endian: The least significant byte is stored first.
 * byteswap(): This method changes the byte order of the array elements in-place. It flips the order of bytes within each element.

13. What is the significance of the np.linalg.inv function?


The np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix. Its significance lies in its applications in various fields, including:
1. Solving Systems of Linear Equations:
 * If you have a system of linear equations represented as Ax = b, where A is a square matrix of coefficients, x is the vector of unknowns, and b is the vector of constants, you can solve for x by calculating the inverse of A: x = A⁻¹b.
2. Finding the Inverse of a Transformation:
 * In linear algebra, matrices can represent linear transformations. The inverse of a matrix represents the inverse transformation. If you have a transformation matrix, finding its inverse allows you to reverse the transformation.
3. Calculating Covariance Matrices:
 * In statistics and machine learning, covariance matrices are used to describe the relationships between variables. The inverse of a covariance matrix is used in various statistical calculations, such as computing the Mahalanobis distance.
4. Matrix Division (in a sense):
 * While you can't directly "divide" matrices, you can use the inverse to achieve an equivalent result. If you want to solve for X in the equation AX = B, you can multiply both sides by the inverse of A: X = A⁻¹B.
5. Optimization Problems:
 * In many optimization problems, particularly those involving quadratic functions, the inverse of a Hessian matrix (a matrix of second-order partial derivatives) is used to find the minimum or maximum of the function.

14. What does the np.reshape function do, and how is it used?


The np.reshape() function in NumPy is used to give a new shape to an array without changing its data. It essentially rearranges the elements of an array into a different configuration.
How it works:
 * Input: It takes an array and a new shape (a tuple of integers) as input.
 * Output: It returns a new array object with the specified shape.
 * Data Preservation: The total number of elements in the original array and the reshaped array must be the same. The function only changes the organization of the elements, not the elements themselves.

In [38]:
# Changing array dimension
arr = np.arange(8)
reshaped_arr = arr.reshape((2,4))
print(f"Reshaped array : \n{reshaped_arr}")

#Flattening Arrays

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
flatten_arr = arr.reshape(-1)
print(f"flatten Array : {flatten_arr}")

Reshaped array : 
[[0 1 2 3]
 [4 5 6 7]]
flatten Array : [1 2 3 4 5 6 7 8 9]


15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays with different shapes. It automatically expands the smaller array to match the shape of the larger array, without actually creating copies of the data.
How it Works:
NumPy follows a set of rules to determine if broadcasting is possible between two arrays:
 * Dimension Compatibility: The dimensions of the arrays must be compatible. This means:
   * Either the dimensions are equal, or
   * One of them is 1.
 * Alignment from Right: NumPy compares the dimensions of the arrays from right to left (trailing dimensions first).

In [39]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
scalar = 10

result = arr + scalar #Broadcasting

print(result)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
